Repository Project-Unifest/unifest-ios, pull requests merged in 2025-08, with the labels that each got.

#77 [Fix] #75 홈 API decoding 오류 해결
  unifest-ios/Networking/APIManager.swift
Labels: Fix

#82 [Feat] 가천대를 자동으로 관심 축제에 등록하는 기능 추가
  unifest-ios/AppDelegate.swift
  unifest-ios/Networking/APIManager.swift
Labels: Feat

#91 [Feat&Release] 설문조사 페이지로의 리디렉션 메뉴 추가 및 즉시 출시에 따른 버전 판올림
  unifest-ios.xcodeproj/project.pbxproj
  unifest-ios/Assets.xcassets/ImageSet/Etc/WhoAreULogo.imageset/Contents.json
  unifest-ios/Assets.xcassets/ImageSet/Etc/WhoAreULogo.imageset/Group 1707480847.svg
  unifest-ios/Assets.xcassets/ImageSet/Etc/WhoAreULogo.imageset/Group 1707480848.svg
  unifest-ios/Views/Menu/MenuView.swift
Labels: Feat, Distribute
